version: '3.3'

services:
    db:
     image: mysql:8.0.17
     volumes:
       - db_data:/var/lib/mysql
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: phanbook
       MYSQL_USER: phanbook
       MYSQL_PASSWORD: secret
     ports:
       - 3307:3306
    php:
     depends_on:
       - db
       - redis
     image: gsviec/php:7.3-alpine
     ports:
       - "8080:80"
     volumes:
      - ./:/app
     env_file:
       - .env
    nginx:
      depends_on:
        - php
      image: nginx
      ports:
          - "80:80"
      working_dir: /var/www/phanbook
      volumes:
        - ./:/var/www/phanbook
        - ./docker/phanbook.conf:/etc/nginx/conf.d/default.conf
    phpmyadmin:
      restart: 'no'
      image: phpmyadmin/phpmyadmin:4.6
      depends_on:
        - db
      ports:
        - "9090:80"
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: secret
    redis:
      image: redis:alpine
      ports:
        - '6378:6379'
volumes:
    db_data:
